/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.token.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.poplogic.blipin.api.token.models.RenewAccessTokenRequest

class RenewAccessTokenRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RenewAccessTokenRequest
        //val modelInstance = RenewAccessTokenRequest()

        // to test the property `refreshToken` - Valid refresh JWT issued to the user.
        should("test refreshToken") {
            // uncomment below to test the property
            //modelInstance.refreshToken shouldBe ("TODO")
        }

    }
}
