/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.auth.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.poplogic.blipin.api.auth.apis.AuthApi
import com.poplogic.blipin.api.auth.models.AuthApplePost200Response
import com.poplogic.blipin.api.auth.models.EmailLoginRequest
import com.poplogic.blipin.api.auth.models.EmailLoginResponse
import com.poplogic.blipin.api.auth.models.ErrorResponse
import com.poplogic.blipin.api.auth.models.GoogleLoginRequest
import com.poplogic.blipin.api.auth.models.GoogleLoginResponse
import com.poplogic.blipin.api.auth.models.VerifyEmailRequest
import com.poplogic.blipin.api.auth.models.VerifyEmailResponse

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test authApplePost
        should("test authApplePost") {
            // uncomment below to test authApplePost
            //val result : AuthApplePost200Response = apiInstance.authApplePost()
            //result shouldBe ("TODO")
        }

        // to test authEmailLoginPost
        should("test authEmailLoginPost") {
            // uncomment below to test authEmailLoginPost
            //val emailLoginRequest : EmailLoginRequest =  // EmailLoginRequest | 
            //val result : EmailLoginResponse = apiInstance.authEmailLoginPost(emailLoginRequest)
            //result shouldBe ("TODO")
        }

        // to test authEmailVerifyPost
        should("test authEmailVerifyPost") {
            // uncomment below to test authEmailVerifyPost
            //val verifyEmailRequest : VerifyEmailRequest =  // VerifyEmailRequest | 
            //val result : VerifyEmailResponse = apiInstance.authEmailVerifyPost(verifyEmailRequest)
            //result shouldBe ("TODO")
        }

        // to test authGooglePost
        should("test authGooglePost") {
            // uncomment below to test authGooglePost
            //val googleLoginRequest : GoogleLoginRequest =  // GoogleLoginRequest | 
            //val result : GoogleLoginResponse = apiInstance.authGooglePost(googleLoginRequest)
            //result shouldBe ("TODO")
        }

    }
}
