/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.user.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.poplogic.blipin.api.user.models.UpdateUserProfileRequest

class UpdateUserProfileRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateUserProfileRequest
        //val modelInstance = UpdateUserProfileRequest()

        // to test the property `displayName` - Optional display name.
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `birthdate` - Optional birthdate in YYYY-MM-DD or RFC3339 format.
        should("test birthdate") {
            // uncomment below to test the property
            //modelInstance.birthdate shouldBe ("TODO")
        }

        // to test the property `gender` - Optional gender value. Matching is case-insensitive in the implementation.
        should("test gender") {
            // uncomment below to test the property
            //modelInstance.gender shouldBe ("TODO")
        }

    }
}
