/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.auth.models

import com.poplogic.blipin.api.auth.models.User
import com.poplogic.blipin.api.auth.models.UserIdentity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param user 
 * @param userIdentity 
 * @param accessToken 
 * @param refreshToken 
 * @param accessTokenExpiresAt 
 * @param refreshTokenExpiresAt 
 * @param sessionId 
 * @param isFirstTimeLogin 
 */
@Serializable

data class GoogleLoginResponse (

    @SerialName(value = "user")
    val user: User,

    @SerialName(value = "user_identity")
    val userIdentity: UserIdentity,

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String,

    @Contextual @SerialName(value = "access_token_expires_at")
    val accessTokenExpiresAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "refresh_token_expires_at")
    val refreshTokenExpiresAt: kotlin.time.Instant,

    @SerialName(value = "session_id")
    val sessionId: kotlin.String,

    @SerialName(value = "is_first_time_login")
    val isFirstTimeLogin: kotlin.Boolean

) {


}

