/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.auth.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param refreshToken 
 * @param userAgent 
 * @param clientIp 
 * @param isBlocked 
 * @param expiresAt 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class Session (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "user_id")
    val userId: kotlin.Long,

    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String,

    @SerialName(value = "user_agent")
    val userAgent: kotlin.String,

    @SerialName(value = "client_ip")
    val clientIp: kotlin.String,

    @SerialName(value = "is_blocked")
    val isBlocked: kotlin.Boolean,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.time.Instant

) {


}

