/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.auth.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param provider 
 * @param providerSub 
 * @param providerEmail 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class UserIdentity (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "user_id")
    val userId: kotlin.Long,

    @SerialName(value = "provider")
    val provider: UserIdentity.Provider,

    @SerialName(value = "provider_sub")
    val providerSub: kotlin.String,

    @SerialName(value = "provider_email")
    val providerEmail: kotlin.String?,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.time.Instant

) {

    /**
     * 
     *
     * Values: google,apple,local_email
     */
    @Serializable
    enum class Provider(val value: kotlin.String) {
        @SerialName(value = "google") google("google"),
        @SerialName(value = "apple") apple("apple"),
        @SerialName(value = "local_email") local_email("local_email");
    }

}

