/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.auth.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param displayName 
 * @param avatarUrl 
 * @param birthdate String date in YYYY-MM-DD or RFC3339, stored as a date field.
 * @param gender Nullable gender value. When unset, the API returns null.
 * @param status 
 * @param createdAt 
 * @param updatedAt 
 * @param deletedAt 
 */
@Serializable

data class User (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "display_name")
    val displayName: kotlin.String?,

    @SerialName(value = "avatar_url")
    val avatarUrl: kotlin.String?,

    /* String date in YYYY-MM-DD or RFC3339, stored as a date field. */
    @Contextual @SerialName(value = "birthdate")
    val birthdate: kotlinx.datetime.LocalDate?,

    /* Nullable gender value. When unset, the API returns null. */
    @SerialName(value = "gender")
    val gender: User.Gender?,

    @SerialName(value = "status")
    val status: User.Status,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "deleted_at")
    val deletedAt: kotlin.time.Instant?

) {

    /**
     * Nullable gender value. When unset, the API returns null.
     *
     * Values: male,female,other
     */
    @Serializable
    enum class Gender(val value: kotlin.String) {
        @SerialName(value = "male") male("male"),
        @SerialName(value = "female") female("female"),
        @SerialName(value = "other") other("other");
    }
    /**
     * 
     *
     * Values: active,inactive,suspended,deleted
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "active") active("active"),
        @SerialName(value = "inactive") inactive("inactive"),
        @SerialName(value = "suspended") suspended("suspended"),
        @SerialName(value = "deleted") deleted("deleted");
    }

}

