/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.auth.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param email 
 * @param code 
 * @param expiresAt 
 * @param createdAt 
 */
@Serializable

data class VerifyEmail (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "user_id")
    val userId: kotlin.Long,

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "code")
    val code: kotlin.String,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant

) {


}

