/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.token.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.poplogic.blipin.api.token.apis.TokenApi
import com.poplogic.blipin.api.token.models.ErrorResponse
import com.poplogic.blipin.api.token.models.RenewAccessTokenRequest
import com.poplogic.blipin.api.token.models.RenewAccessTokenResponse
import com.poplogic.blipin.api.token.models.RevokeTokenResponse

class TokenApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TokenApi
        //val apiInstance = TokenApi()

        // to test tokenRenewAccessTokenPost
        should("test tokenRenewAccessTokenPost") {
            // uncomment below to test tokenRenewAccessTokenPost
            //val renewAccessTokenRequest : RenewAccessTokenRequest =  // RenewAccessTokenRequest | 
            //val result : RenewAccessTokenResponse = apiInstance.tokenRenewAccessTokenPost(renewAccessTokenRequest)
            //result shouldBe ("TODO")
        }

        // to test tokenRevokePost
        should("test tokenRevokePost") {
            // uncomment below to test tokenRevokePost
            //val result : RevokeTokenResponse = apiInstance.tokenRevokePost()
            //result shouldBe ("TODO")
        }

    }
}
