/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.user.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.poplogic.blipin.api.user.apis.UserApi
import com.poplogic.blipin.api.user.models.ErrorResponse
import com.poplogic.blipin.api.user.models.GetUserProfileResponse
import com.poplogic.blipin.api.user.models.UpdateUserProfileRequest
import com.poplogic.blipin.api.user.models.UpdateUserProfileResponse

class UserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserApi
        //val apiInstance = UserApi()

        // to test userGet
        should("test userGet") {
            // uncomment below to test userGet
            //val result : GetUserProfileResponse = apiInstance.userGet()
            //result shouldBe ("TODO")
        }

        // to test userPut
        should("test userPut") {
            // uncomment below to test userPut
            //val updateUserProfileRequest : UpdateUserProfileRequest =  // UpdateUserProfileRequest | 
            //val result : UpdateUserProfileResponse = apiInstance.userPut(updateUserProfileRequest)
            //result shouldBe ("TODO")
        }

    }
}
