/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.auth.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.poplogic.blipin.api.auth.models.EmailLoginResponse

class EmailLoginResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EmailLoginResponse
        //val modelInstance = EmailLoginResponse()

        // to test the property `isNewUser`
        should("test isNewUser") {
            // uncomment below to test the property
            //modelInstance.isNewUser shouldBe ("TODO")
        }

    }
}
