/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.auth.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.poplogic.blipin.api.auth.models.VerifyEmailResponse
import com.poplogic.blipin.api.auth.models.User

class VerifyEmailResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VerifyEmailResponse
        //val modelInstance = VerifyEmailResponse()

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `accessToken`
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `refreshToken`
        should("test refreshToken") {
            // uncomment below to test the property
            //modelInstance.refreshToken shouldBe ("TODO")
        }

        // to test the property `accessTokenExpiresAt`
        should("test accessTokenExpiresAt") {
            // uncomment below to test the property
            //modelInstance.accessTokenExpiresAt shouldBe ("TODO")
        }

        // to test the property `refreshTokenExpiresAt`
        should("test refreshTokenExpiresAt") {
            // uncomment below to test the property
            //modelInstance.refreshTokenExpiresAt shouldBe ("TODO")
        }

        // to test the property `sessionId`
        should("test sessionId") {
            // uncomment below to test the property
            //modelInstance.sessionId shouldBe ("TODO")
        }

    }
}
