# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build and distribute stagingValidation APK"
    lane :staging_validation_apk do
      gradle(
        task: "assemble",
        build_type: "validation",
        flavor: "staging"
      )
      apk = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

      firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        service_credentials_file: ENV["FIREBASE_CREDENTIALS_JSON_PATH"],
        groups: "internal-testers",
        release_notes: "CI build from develop branch",
        apk_path: apk
      )
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
