# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Get the last commit message from the current branch"
  lane :get_branch_last_commit do
      last_commit = `git log -1 --pretty=%B`.strip
      UI.message("Last commit message: #{last_commit}")
      last_commit
  end

  desc "Build and distribute stagingValidation APK"
    lane :staging_validation_apk do

#       increment_version
      gradle(
        task: "assemble",
        build_type: "validation",
        flavor: "staging"
      )
      apk = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
      UI.user_error!("APK output path was not found after assemble.") unless apk

      firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        service_credentials_file: ENV["FIREBASE_CREDENTIALS_JSON_PATH"],
        groups: "internal-testers-1",
        release_notes: get_branch_last_commit,
        apk_path: apk
      )

#       discord_webhook(
#         url: ENV["DISCORD_WEBHOOK_URL"],
#         username: "Staging Validation Bot",
#         content: "A new staging validation APK has been uploaded to Firebase App Distribution. Check it out: #{apk}"
#       )
      require "json"

      sh(%Q(curl -sS -X POST "#{ENV["DISCORD_WEBHOOK_URL"]}" \
        -H "Content-Type: application/json" \
        -d '#{{
          username: "Staging Validation Bot",
          content: "A new staging validation APK has been uploaded to Firebase App Distribution. Check it out: #{apk}"
        }.to_json}'))
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end


#   desc "Increment the build number based on the latest release in Firebase App Distribution"
#   lane :increment_version do
#     latest_release = firebase_app_distribution_get_latest_release(
#       app: ENV["FIREBASE_APP_ID"],
#       service_credentials_file: ENV["FIREBASE_CREDENTIALS_JSON_PATH"]
#     )
#     latest_build = latest_release && latest_release[:buildVersion] ? latest_release[:buildVersion].to_i : 0
#     increment_build_number(build_number: latest_build + 1)
#   end
end
