/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.user.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param displayName Display name to set. Use null to clear it.
 * @param birthdate Birthdate in YYYY-MM-DD or RFC3339 format. Use null to clear it.
 * @param gender Gender value. Matching is case-insensitive in the implementation. Use null to clear it.
 */
@Serializable

data class UpdateUserProfileRequest (

    /* Display name to set. Use null to clear it. */
    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null,

    /* Birthdate in YYYY-MM-DD or RFC3339 format. Use null to clear it. */
    @SerialName(value = "birthdate")
    val birthdate: kotlin.String? = null,

    /* Gender value. Matching is case-insensitive in the implementation. Use null to clear it. */
    @SerialName(value = "gender")
    val gender: UpdateUserProfileRequest.Gender? = null

) {

    /**
     * Gender value. Matching is case-insensitive in the implementation. Use null to clear it.
     *
     * Values: male,female,other
     */
    @Serializable
    enum class Gender(val value: kotlin.String) {
        @SerialName(value = "male") male("male"),
        @SerialName(value = "female") female("female"),
        @SerialName(value = "other") other("other");
    }

}

