/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.token.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accessToken 
 * @param accessTokenExpiresAt 
 * @param refreshToken Rotated refresh token.
 * @param refreshTokenExpiresAt 
 */
@Serializable

data class RenewAccessTokenResponse (

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @Contextual @SerialName(value = "access_token_expires_at")
    val accessTokenExpiresAt: kotlin.time.Instant,

    /* Rotated refresh token. */
    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String,

    @Contextual @SerialName(value = "refresh_token_expires_at")
    val refreshTokenExpiresAt: kotlin.time.Instant

) {


}

