/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.poplogic.blipin.api.user.apis

import com.poplogic.blipin.api.user.models.ErrorResponse
import com.poplogic.blipin.api.user.models.GetUserProfileResponse
import com.poplogic.blipin.api.user.models.UpdateUserProfileRequest
import com.poplogic.blipin.api.user.models.UpdateUserProfileResponse

import com.poplogic.blipin.api.user.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class UserApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /user
        * Get current user profile
        * Fetches the authenticated user&#39;s profile based on the JWT payload.
         * @return GetUserProfileResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun userGet(): HttpResponse<GetUserProfileResponse> {

            val localVariableAuthNames = listOf<String>("BearerAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/user",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * PATCH /user
        * Update current user profile
        * Applies a JSON Merge Patch to the authenticated user&#39;s profile. Include only fields you want to change. Set a field to null to clear it. Supported fields are display_name, birthdate, and gender. Birthdate accepts YYYY-MM-DD or RFC3339 and gender must be male, female, or other. 
         * @param updateUserProfileRequest  
         * @return UpdateUserProfileResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun userPatch(updateUserProfileRequest: UpdateUserProfileRequest): HttpResponse<UpdateUserProfileResponse> {

            val localVariableAuthNames = listOf<String>("BearerAuth")

            val localVariableBody = updateUserProfileRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/user",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
