name: Android CI/CD

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on:
      group: Blipin-Client
      labels: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle build (stagingValidation)
        run: ./gradlew assembleStagingValidation

      - name: Zipalign APK
        run: |
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 \
            app/build/outputs/apk/stagingValidation/app-staging-*.apk \
            app/build/outputs/apk/stagingValidation/app-staging-aligned.apk

      - name: Sign APK
        run: |
          apksigner sign \
            --ks ${{ secrets.SIGNING_KEYSTORE_PATH }} \
            --ks-pass pass:${{ secrets.SIGNING_STORE_PASSWORD }} \
            --key-pass pass:${{ secrets.SIGNING_KEY_PASSWORD }} \
            --ks-key-alias ${{ secrets.SIGNING_KEY_ALIAS }} \
            --out app/build/outputs/apk/stagingValidation/app-staging-signed.apk \
            app/build/outputs/apk/stagingValidation/app-staging-aligned.apk

      - name: Verify APK signature
        run: apksigner verify --verbose app/build/outputs/apk/stagingValidation/app-staging-signed.apk

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          groups: testers
          file: app/build/outputs/apk/stagingValidation/app-staging-signed.apk.apk
